# Usamos una imagen ligera de Python
FROM python:3.9-slim

# Creamos el directorio de trabajo
WORKDIR /app

# Copiamos el archivo de requisitos e instalamos dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el código de la aplicación
COPY app.py .

# Exponemos el puerto interno que usará Flask
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]
